---
abstract: "Handling module for the clustering tool 'Bayon'"
author:
  - 'Takeshi Miki <t.miki@nttr.co.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Bayon
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  File::Temp: 0
  Filter::Util::Call: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00002
